# Site settings
title: Säven Seltzer
email: hello@savenseltzer.com
email_hello: hello@savenseltzer.com
email_info: info@savenseltzer.com
url: https://www.savenseltzer.com
description: "Sparkingly fresh seltzer from the deep forests of Sweden"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#2F4858"
  primary-light: "#fff"
  blue: "#33658A"
  light-blue: "#86BBD8"
  yellow: "#F6AE2D"
  green: "#9BC53D"
  red: "red"
  orange: "#F26419"
  links: "#F6AE2D"

# Footer settings
footer: "Saven Beverages Ltd"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/savenseltzer
  - title: instagram
    url: https://instagram.com/savenseltzer

# Build settings
markdown: kramdown
permalink: pretty

include:
  - .well-known
